account/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = "account"

urlpatterns = [
    path("profile/<int:pk>", views.UserProfileView.as_view(), name="profile"),
    path("signup/", views.user_signup, name="signup"),
    path("login/", views.user_login, name="login"),
    path("logout/", views.user_logout, name="logout"),
    path(
        "password_change/",
        auth_views.PasswordChangeView.as_view(),
        name="password_change",
    ),
    path(
        "password_change/done/",
        auth_views.PasswordChangeDoneView.as_view(),
        name="password_change_done",
    ),
]

mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from debug_toolbar.toolbar import debug_toolbar_urls

urlpatterns = [
    path("admin/", admin.site.urls),
    path("polls/", include("polls.urls")),
    path("", include("account.urls")),
]

if not settings.TESTING:
    urlpatterns += debug_toolbar_urls()

if not settings.PRODUCTION:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

polls/urls.py
from django.urls import path
from . import views

app_name = "polls"

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("secured/", views.secured, name="secured"),
    path("<int:question_id>/", views.DetailView.as_view(), name="detail"),
    path("<int:question_id>/results/", views.ResultsView.as_view(), name="results"),
    path("<int:question_id>/vote/", views.vote, name="vote"),
]

account/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User


class ProfileModel(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    avatar = models.ImageField(upload_to="avatars/%Y", null=True, blank=True)

    def get_absolute_url(self):
        return reverse("account:profile", kwargs={"pk": self.id})

polls/models.py
import datetime

from django.db import models
from django.utils import timezone
from django.contrib import admin


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField("date published")

    def __str__(self):
        return self.question_text[:5] + "..."

    @admin.display(
        boolean=True,
        ordering="pub_date",
        description="Published recently?",
    )
    def was_published_recently(self):
        return (
            datetime.timedelta(days=0)
            < (timezone.now() - self.pub_date)
            < datetime.timedelta(days=5)
        )


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return (
            f"{self.choice_text[:5]} (Question {self.question.id}, Votes: {self.votes})"
        )

account/forms.py
from django.contrib.auth.models import User
from django import forms
from .models import ProfileModel


class LoginForm(forms.Form):
    username = forms.CharField(min_length=3, max_length=40)
    password = forms.CharField(widget=forms.PasswordInput)


class SignupForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ["username", "email"]

    password = forms.CharField(widget=forms.PasswordInput)
    password_confirm = forms.CharField(
        widget=forms.PasswordInput, label="Password Repeat"
    )

    def clean_password_confirm(self):
        cleaned = self.cleaned_data
        if cleaned["password"] != cleaned["password_confirm"]:
            raise forms.ValidationError("Password doesn't match")
        return cleaned["password_confirm"]


class ProfileForm(forms.ModelForm):
    class Meta:
        model = ProfileModel
        fields = ["user", "avatar"]

account/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate, logout
from django.views.generic.edit import UpdateView

from .forms import LoginForm, SignupForm, ProfileForm
from .models import ProfileModel
from .mixins import UserRelatedMixin


class UserProfileView(UserRelatedMixin, UpdateView):
    model = ProfileModel
    form_class = ProfileForm
    # fields = ["user", "avatar"]


def user_logout(request):
    logout(request)
    return render(request, "account/logout.html")


def user_signup(request):
    if request.method == "GET":
        return render(request, "account/signup.html", {"form": SignupForm()})

    form = SignupForm(request.POST)

    if not form.is_valid():
        return render(
            request,
            "account/signup.html",
            {"error_message": form.errors.as_text(), "form": SignupForm()},
        )

    new_user = form.save(commit=False)
    new_user.set_password(form.cleaned_data["password_confirm"])
    new_user.save()
    ProfileModel.objects.create(user=new_user)

    # if not user:
    #     return render(
    #         request,
    #         "account/signup.html",
    #         {"error_message": "Not found. Try again.", "form": SignupForm()},
    #     )

    # if not user.is_active:
    #     return render(
    #         request,
    #         "account/signup.html",
    #         {"error_message": "Account isn't activated yet.", "form": SignupForm()},
    #     )

    return redirect("account:login")


def user_login(request):
    if request.method == "GET":
        return render(request, "account/login.html", {"form": LoginForm()})

    form = LoginForm(request.POST)

    if not form.is_valid():
        return render(
            request,
            "account/login.html",
            {"error_message": form.errors.as_text(), "form": LoginForm()},
        )

    user = authenticate(
        request,
        username=form.cleaned_data["username"],
        password=form.cleaned_data["password"],
    )

    if not user:
        return render(
            request,
            "account/login.html",
            {"error_message": "Not found. Try again.", "form": LoginForm()},
        )

    if not user.is_active:
        return render(
            request,
            "account/login.html",
            {"error_message": "Account isn't activated yet.", "form": LoginForm()},
        )

    login(request, user)

    return redirect("polls:index")

polls/views.py
from django.db.models import F
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.views import generic
from django.utils import timezone
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404
from . import models


class IndexView(generic.ListView):
    context_object_name = "two_recent_questions"

    def get_queryset(self):
        return models.Question.objects.filter(pub_date__lte=timezone.now()).order_by(
            "-pub_date"
        )[:2]


class DetailView(LoginRequiredMixin, generic.DetailView):
    pk_url_kwarg = "question_id"

    def get_queryset(self):
        return models.Question.objects.filter(pub_date__lte=timezone.now())


class ResultsView(generic.DetailView):
    template_name = "polls/results.html"
    model = models.Question
    context_object_name = "question_results"
    pk_url_kwarg = "question_id"


def vote(request, question_id):
    question = get_object_or_404(models.Question, id=question_id)
    try:
        selected_choice_id = request.POST.get("choice")
        selected_choice = question.choice_set.get(id=selected_choice_id)
    except (KeyError, models.Choice.DoesNotExist):
        return render(
            request,
            "polls/detail.html",
            {"question": question, "error_message": "No choice selected"},
        )
    else:
        selected_choice.votes = F("votes") + 1
        selected_choice.save()
        return HttpResponseRedirect(reverse("polls:results", args=(question_id,)))


@login_required
def secured(request):
    return HttpResponse("Here")

account/templates/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="{% static 'polls/global.css' %}">
  <link href="https://cdn.jsdelivr.net/npm/daisyui@5" rel="stylesheet" type="text/css" />
  <script src="https://cdn.jsdelivr.net/npm/@tailwindcss/browser@4"></script>
  {% block 'css' %}{% endblock %}
  <title>{% block 'title' %}{% endblock %}</title>
</head>

<body>
  <div class="navbar bg-base-100 shadow-sm">
    <div class="flex-1">
      <a class="btn btn-ghost text-xl">Polls</a>
    </div>
    <div class="flex-none">
      <ul class="menu menu-horizontal px-1">
        <li>
          <a href="{% url "polls:index" %}">To polls list</a>
        </li>
        <li>
          <a href="{% url "polls:index" %}">To polls list</a>
        </li>
      </ul>
    </div>
  </div>

  {% block 'main' %}{% endblock %}
  {% block 'js' %}{% endblock %}
</body>

</html>

polls/templates/polls/detail.html
<form action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}
    <fieldset>
        <legend>
            <h1>{{ question.question_text }}</h1>
        </legend>
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
        {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
        {% endfor %}
    </fieldset>
    <input type="submit" value="Vote">
</form>

polls/templates/polls/index.html
{% if not recent_questions %}
<h2>No recent posts...</h2>
{% else %}
<h2>Recent posts</h2>
{% for question in recent_questions %}
<p>
    <a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a>
</p>
{% endfor %}
{% endif %}

polls/templates/polls/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="{% static 'polls/global.css' %}">
  <link href="https://cdn.jsdelivr.net/npm/daisyui@5" rel="stylesheet" type="text/css" />
  <script src="https://cdn.jsdelivr.net/npm/@tailwindcss/browser@4"></script>
  {% block 'css' %}{% endblock %}
  <title>{% block 'title' %}{% endblock %}</title>
</head>

<body>
  <div class="navbar bg-base-100 shadow-sm">
    <div class="flex-1">
      <a class="btn btn-ghost text-xl">Polls</a>
    </div>
    <div class="flex-none">
      <ul class="menu menu-horizontal px-1">
        <li>
          <a href="{% url "polls:index" %}">To polls list</a>
        </li>
        <li>
          <a href="{% url "polls:index" %}">To polls list</a>
        </li>
        {% if request.user.is_authenticated %}
        <li>{{ request.user.username }}</li>
        {% endif %}
          <li>
            {% if request.user.is_authenticated %}
            <a href="{% url "account:logout" %}">Logout</a>
            {% else %}
            <a href="{% url "account:login" %}">Login</a>
            <a href="{% url "account:signup" %}">Signup</a>
            {% endif %}
          </li>
      </ul>
    </div>
  </div>

  {% block 'main' %}{% endblock %}
  {% block 'js' %}{% endblock %}
</body>

</html>

polls/templates/polls/question_detail.html
{% extends "polls/layout.html" %}

{% block 'title' %}Poll results{% endblock %}

{% block 'main' %}
<form action="{% url 'polls:vote' question.id %}" method="post">
  {% csrf_token %}
  <fieldset>
    <legend>
      <h1>{{ question.question_text }}</h1>
    </legend>
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    {% for choice in question.choice_set.all %}
    <label for="choice{{ forloop.counter }}" class="m-2">
      <span class="label">{{ choice.choice_text }}/</span>
      <input type="radio" class="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
    </label>
    {% endfor %}
  </fieldset>
  <button class="btn btn-primary" type="submit">Vote</button>
</form>
{% endblock %}

polls/templates/polls/question_list.html
{% extends "polls/layout.html" %}

{% block 'title' %}Recent polls{% endblock %}

{% block 'main' %}
{% if not two_recent_questions %}
<h2>No recent polls...</h2>
{% else %}

<ul class="list bg-base-100 rounded-box shadow-md">
  <li class="p-4 pb-2 text-xs opacity-60 tracking-wide">Recent polls</li>
  {% for question in two_recent_questions %}
  <li class="list-row">
    <div class="text-4xl font-thin opacity-30 tabular-nums">{{ forloop.counter }}</div>
    <div><img class="size-10 rounded-box" src="https://img.daisyui.com/images/profile/demo/1@94.webp" /></div>
    <div class="list-col-grow">
      <div>{{ question.question_text }}</div>
      <div class="text-xs uppercase font-semibold opacity-60">{{ question.question_text }}n</div>
    </div>
    <a class="btn btn-square btn-ghost" href="{% url 'polls:detail' question.id %}">
      <svg class="size-[1.2em]" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
        <g stroke-linejoin="round" stroke-linecap="round" stroke-width="2" fill="none" stroke="currentColor">
          <path d="M6 3L20 12 6 21 6 3z"></path>
        </g>
      </svg>
    </a>
    <button>

    </button>
  </li>
  {% endfor %}
  {% endif %}
  {% endblock %}

polls/templates/polls/results.html
{% extends "polls/layout.html" %}

{% block 'title' %}Poll results{% endblock %}

{% block 'main' %}
<h1>{{ question_results.question_text }}</h1>
<ul>
{% for choice in question_results.choice_set.all %}
    <li>{{ choice.choice_text }} - {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>
<a href="{% url 'polls:detail' question_results.id %}">Vote again?</a>
{% endblock %}